title: NTDs
modelClass: abuseio\scart\models\Ntd
customViewPath: '$/abuseio/scart/layouts/scart/list'
list: $/abuseio/scart/models/ntd/columns.yaml
recordUrl: 'abuseio/scart/ntds/preview/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
filter: config_filter.yaml
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
defaultSort: 'filenumber asc'
