logs:
  label: log
  modelClass: abuseio\scart\models\Log
  readOnly: true
  view:
    list: $/abuseio/scart/models/log/columns.yaml
    showSorting: false
    recordsPerPage: 5
ntd_urls:
  label: ntd_urls
  modelClass: abuseio\scart\models\Ntd_url
  readOnly: true
  view:
    list: $/abuseio/scart/models/ntd/columns_ntd_urls.yaml
    showCheckboxes: false
    showSorting: false
    recordsPerPage: 10
