list: $/abuseio/scart/models/maintenance/columns.yaml
modelClass: abuseio\scart\Models\Maintenance
title: Maintenance
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'abuseio/scart/maintenance/update/:id'
