displaycolumn:
    1920:
        2:
            colspan: 6
            boxheightsize: 550
            imgsize: 530
            txtsize: 85
        3:
            colspan: 4
            boxheightsize: 550
            imgsize: 480
            txtsize: 55
        4:
            colspan: 3
            boxheightsize: 450
            imgsize: 380
            txtsize: 40
    1620:
        2:
            colspan: 6
            boxheightsize: 500
            imgsize: 480
            txtsize: 61
        3:
            colspan: 4
            boxheightsize: 400
            imgsize: 380
            txtsize: 37
        4:
            colspan: 3
            boxheightsize: 400
            imgsize: 350
            txtsize: 30
    1020:
        2:
            colspan: 6
            boxheightsize: 500
            imgsize: 480
            txtsize: 42
        3:
            colspan: 4
            boxheightsize: 400
            imgsize: 380
            txtsize: 22
        4:
            colspan: 3
            boxheightsize: 400
            imgsize: 300
            txtsize: 17
    0:
        2:
            colspan: 12
            boxheightsize: 400
            imgsize: 100
            txtsize: 20
        3:
            colspan: 4
            boxheightsize: 400
            imgsize: 380
            txtsize: 20
        4:
            colspan: 6
            boxheightsize: 400
            imgsize: 100
            txtsize: 20
