list: $/abuseio/scart/models/input/columns_viewpolice.yaml
modelClass: abuseio\scart\models\Input
title: Police
noRecordsMessage: 'backend::lang.list.no_records'
customViewPath: '$/abuseio/scart/layouts/scart/list'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'abuseio/scart/police/preview/:id'
