columns:
    filenumber:
        label: filenumber
        type: text
        width: 8%
        searchable: true
    reference:
        label: 'external reference'
        type: text
        width: 8%
    url:
        label: url
        type: text
        width: 60%
        searchable: true
    status_code:
        label: status
        type: text
        relation: inputStatus
        select: title
        width: 8%
        searchable: true
    grade_code:
        label: 'classification'
        type: text
        width: 8%
        searchable: true
        clickable: false
    firstseen_at:
        label: 'first seen'
        type: text
        width: 8%
        searchable: true
        clickable: false
