columns:
    updated_at:
        label: timestamp
        type: datetime
        width: 15%
        clickable: false
    user:
        label: user
        type: text
        relation: user
        select: login
        searchable: true
        width: 10%
        clickable: false
    logtext:
        label: logtext
        type: text
        width: 65%
        clickable: false
