list: $/abuseio/scart/models/ntdtemplate/columns.yaml
modelClass: abuseio\scart\models\NTDtemplate
title: NTDtemplates
noRecordsMessage: 'backend::lang.list.no_records'
customViewPath: '$/abuseio/scart/layouts/scart/list'
showSetup: false
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'abuseio/scart/ntdtemplates/update/:id'
