list: $/abuseio/scart/models/user/columns.yaml
modelClass: abuseio\scart\models\User
title: Users
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: false
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'abuseio/scart/users/update/:id'
