fields:
    created_at:
        span: left
        label: 'start'
        relation: input_history
        select: created_at
        type: text
        readOnly: true
    online_counter:
        span: right
        label: 'Online Counter'
        type: text
        readOnly: true



