scopes:
  source_code:
    label: 'source'
    type: group
    conditions: 'source_code in (:filtered)'
    modelClass: abuseio\scart\models\Input_source
    options: getSourceOptions
  received_at:
    label: Date
    type: daterange
    conditions: received_at >= ':after' AND received_at <= ':before'
  url:
    label: url
    type: text
    default:
    conditions: url like concat('%', :value, '%')
    size: 50
