columns:
    updated_at:
        label: timestamp
        type: datetime
        width: 15%
        clickable: false
    logtext:
        label: logtext
        type: text
        width: 65%
        clickable: false
