list: $/abuseio/scart/models/input/columns_view.yaml
modelClass: abuseio\scart\models\Input
customViewPath: '$/abuseio/scart/layouts/scart/list'
title: Changed
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'abuseio/scart/changed/preview/:id'
